name: sisyphus-server

services:
  redis:
    image: eqalpha/keydb:latest 
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    entrypoint: "keydb-server /etc/keydb/keydb.conf --appendonly yes --server-threads 4"
    networks:
      - sisyphus-network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - sisyphus-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongo:27017/"
    depends_on:
      - mongo
    networks:
      - sisyphus-network

  sisyphus-server:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    environment:
      REDIS_URI: "redis://redis:6379"
      MONGO_URI: "mongodb://root:root@mongo:27017"
    networks:
      - sisyphus-network

networks:
  sisyphus-network:

